# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Bad Ball Hitter
paginate:       5
baseurl:        ""
url:            "https://shinye.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Shinye Song
  url:          shinye.github.io
  email:        novembertwentysix@gmail.com

# Custom vars
version:        1.0
github:
  repo:         https://github.com/shinye/shinye.github.io

# Gems
plugins:
  - jekyll-paginate

# Google analytics
google-analytics:
  id: "UA-105708008-1"
